import Anthropic from '@anthropic-ai/sdk';
import { authenticateRequest } from './auth.mjs';

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

const CORS_HEADERS = {
  'Content-Type': 'application/json',
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
};

const MIME_TYPES = {
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  pdf: 'application/pdf',
};

// ============ BUILD EXPORT PROMPTS ============

function buildExportPrompt(format, data, title, kpis, chartDescriptions) {
  const dataPreview = JSON.stringify(data?.slice(0, 50) || [], null, 2);
  const totalRows = data?.length || 0;
  const columns = data?.length > 0 ? Object.keys(data[0]).join(', ') : 'N/A';
  const kpiText = kpis?.length > 0 ? `\nKPIs: ${JSON.stringify(kpis)}` : '';
  const chartText = chartDescriptions?.length > 0 ? `\nCharts: ${JSON.stringify(chartDescriptions)}` : '';

  const prompts = {
    xlsx: `Create a professional Excel spreadsheet titled "${title}".

Content:
- Sheet 1 "Resume": KPIs summary table with key metrics${kpiText}
- Sheet 2 "Donnees": Full data table (${totalRows} rows)
- Sheet 3 "Graphiques": At least 2 charts (bar chart and line chart) based on the data

Columns: ${columns}
Data (${totalRows} rows, showing first 50):
${dataPreview}
${chartText}

Style: Professional formatting with headers in bold, alternating row colors, number formatting, and chart titles in French.
Save the file as "${title}.xlsx".`,

    pptx: `Create a professional PowerPoint presentation titled "${title}".

Slides:
- Slide 1: Title slide with "${title}" and date
- Slide 2: KPIs summary (key metrics in a clean layout)${kpiText}
- Slide 3-4: Key charts and insights from the data${chartText}
- Slide 5: Data summary table (top 10-15 rows)

Columns: ${columns}
Data (${totalRows} rows, showing first 50):
${dataPreview}

Style: Dark professional theme (navy/dark blue background, white text, cyan accents). Charts with clear labels. All text in French.
Save the file as "${title}.pptx".`,

    pdf: `Create a professional PDF report titled "${title}".

Sections:
- Header: Title "${title}" with date
- Section 1: KPIs summary (key metrics with values)${kpiText}
- Section 2: Charts (at least 2 charts visualizing the data)${chartText}
- Section 3: Data table (first 20-30 rows)
- Footer: Page numbers

Columns: ${columns}
Data (${totalRows} rows, showing first 50):
${dataPreview}

Style: Professional report formatting. Clean layout, readable fonts, proper spacing. All text in French.
Save the file as "${title}.pdf".`,
  };

  return prompts[format] || prompts.xlsx;
}

// ============ EXTRACT FILE ID FROM RESPONSE ============

function extractFileId(response) {
  for (const block of response.content) {
    if (block.type === 'bash_code_execution_tool_result') {
      const result = block.content;
      if (result.type === 'bash_code_execution_result' && result.content) {
        for (const item of result.content) {
          if (item.file_id) return item.file_id;
        }
      }
    }
  }
  return null;
}

// ============ GENERATE EXPORT ============

async function generateExport({ format, data, title, kpis, chartDescriptions }) {
  const skillId = format; // "pptx", "xlsx", or "pdf"
  const prompt = buildExportPrompt(format, data, title, kpis, chartDescriptions);

  console.log(`Generating ${format} export for "${title}" (${data?.length || 0} rows)...`);

  const response = await anthropic.beta.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 8192,
    betas: ['code-execution-2025-08-25', 'skills-2025-10-02', 'files-api-2025-04-14'],
    container: {
      skills: [{ type: 'anthropic', skill_id: skillId, version: 'latest' }],
    },
    tools: [{ type: 'code_execution_20250825', name: 'code_execution' }],
    messages: [{ role: 'user', content: prompt }],
  });

  console.log(`Response: ${response.content.length} blocks, stop_reason: ${response.stop_reason}`);
  console.log(`Tokens: ${response.usage.input_tokens} in / ${response.usage.output_tokens} out`);

  // Extract file_id from response
  const fileId = extractFileId(response);
  if (!fileId) {
    console.error('No file_id found in response');
    throw new Error('No file generated by Claude');
  }

  console.log(`File ID: ${fileId}, downloading...`);

  // Download file content via Files API
  const fileContent = await anthropic.beta.files.download(fileId, {
    betas: ['files-api-2025-04-14'],
  });

  // Convert stream to buffer
  const chunks = [];
  for await (const chunk of fileContent) {
    chunks.push(chunk);
  }
  const buffer = Buffer.concat(chunks);
  console.log(`Downloaded ${buffer.length} bytes`);

  return {
    base64: buffer.toString('base64'),
    filename: `${title}.${format}`,
    mimeType: MIME_TYPES[format],
  };
}

// ============ HANDLER ============

export const handler = async (event) => {
  // CORS preflight
  if (event.requestContext?.http?.method === 'OPTIONS') {
    return { statusCode: 200, headers: CORS_HEADERS, body: '' };
  }

  // Auth
  const { user, error: authError, statusCode: authStatus } = await authenticateRequest(event);
  if (authError) {
    return { statusCode: authStatus, headers: CORS_HEADERS, body: JSON.stringify({ error: authError }) };
  }

  try {
    const body = JSON.parse(event.body || '{}');
    const { format, data, title, kpis, chartDescriptions } = body;

    if (!format || !['xlsx', 'pptx', 'pdf'].includes(format)) {
      return {
        statusCode: 400,
        headers: CORS_HEADERS,
        body: JSON.stringify({ error: 'Invalid format. Use: xlsx, pptx, or pdf' }),
      };
    }

    if (!data || !Array.isArray(data) || data.length === 0) {
      return {
        statusCode: 400,
        headers: CORS_HEADERS,
        body: JSON.stringify({ error: 'No data provided' }),
      };
    }

    const result = await generateExport({ format, data, title: title || 'Dashboard', kpis, chartDescriptions });

    return {
      statusCode: 200,
      headers: CORS_HEADERS,
      body: JSON.stringify(result),
    };
  } catch (err) {
    console.error('Export error:', err);
    return {
      statusCode: 500,
      headers: CORS_HEADERS,
      body: JSON.stringify({ error: err.message || 'Export failed' }),
    };
  }
};
