AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: App Factory - Lambda Backend + Cognito Auth

Parameters:
  AnthropicApiKey:
    Type: String
    NoEcho: true
  PublishBucket:
    Type: String
    Default: ai-app-builder-sk-2026
  MyRegion:
    Type: String
    Default: eu-north-1

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        RULES_BUCKET: !Ref PublishBucket
        PUBLISH_BUCKET: !Ref PublishBucket
        MY_REGION: !Ref MyRegion
        COGNITO_USER_POOL_ID: !Ref CognitoUserPool
        COGNITO_REGION: !Ref MyRegion

Resources:

  # ============ COGNITO ============
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: app-factory-users
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      Schema:
        - Name: email
          Required: true
          Mutable: true
          AttributeDataType: String

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: app-factory-web
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: ENABLED
      AccessTokenValidity: 60
      IdTokenValidity: 60
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days

  # ============ API GATEWAY ============
  AppFactoryApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowHeaders:
          - Content-Type
          - Authorization
        AllowMethods:
          - GET
          - POST
          - OPTIONS

  # ============ GENERATE (Function URL — no 30s timeout) ============
  GenerateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: app-factory-generate
      Handler: index.handler
      CodeUri: generate/
      Timeout: 600
      MemorySize: 512
      Environment:
        Variables:
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'
          AllowHeaders:
            - Content-Type
            - Authorization
          AllowMethods:
            - POST
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref PublishBucket
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Format: esm
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - index.mjs
        External:
          - '@aws-sdk/*'
        Banner:
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);

  # ============ RULES ============
  RulesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: app-factory-rules
      Handler: index.handler
      CodeUri: rules/
      Events:
        Get:
          Type: HttpApi
          Properties:
            ApiId: !Ref AppFactoryApi
            Path: /rules
            Method: GET
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref PublishBucket
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Format: esm
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - index.mjs
        External:
          - '@aws-sdk/*'
        Banner:
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);

  # ============ PUBLISH ============
  PublishFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: app-factory-publish
      Handler: index.handler
      CodeUri: publish/
      Timeout: 60
      MemorySize: 512
      Events:
        Post:
          Type: HttpApi
          Properties:
            ApiId: !Ref AppFactoryApi
            Path: /publish
            Method: POST
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref PublishBucket
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Format: esm
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - index.mjs
        External:
          - '@aws-sdk/*'
        Banner:
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);

  # ============ DB PROXY ============
  DbFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: app-factory-db
      Handler: index.handler
      CodeUri: db/
      Timeout: 30
      MemorySize: 256
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'
          AllowHeaders:
            - Content-Type
            - Authorization
          AllowMethods:
            - POST
      Events:
        Schema:
          Type: HttpApi
          Properties:
            ApiId: !Ref AppFactoryApi
            Path: /db/schema
            Method: POST
        Query:
          Type: HttpApi
          Properties:
            ApiId: !Ref AppFactoryApi
            Path: /db/query
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Format: esm
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - index.mjs
        Banner:
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);

Outputs:
  ApiUrl:
    Description: API Gateway URL (rules + publish + db)
    Value: !Sub 'https://${AppFactoryApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
  GenerateUrl:
    Description: Generate Function URL (no 30s timeout)
    Value: !GetAtt GenerateFunctionUrl.FunctionUrl
  DbProxyUrl:
    Description: DB Proxy Function URL
    Value: !GetAtt DbFunctionUrl.FunctionUrl
  CognitoUserPoolId:
    Description: Cognito User Pool ID (for frontend .env)
    Value: !Ref CognitoUserPool
  CognitoClientId:
    Description: Cognito App Client ID (for frontend .env)
    Value: !Ref CognitoUserPoolClient